In [1]:
import numpy as np
import pandas as pd
import matplotlib as mp

In [2]:
data_base1 = pd.read_csv('../data_core/BostonHousing.csv')
data_base1.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [12]:
# Pandas data structure

## 1. Series - column like
# vals = [i for i in range(0,100,20)]
# #vals  = [10,20,30]
# s = pd.Series(vals, index = ['a','bb','c','d','a'])
# s.loc['a']

## 2. Dataframe - table like
df = pd.DataFrame(
    {
        "age":[x for x in range(50)],
        
        "number": [x for x in range(0,100,2)]
    }
)
df.head()

   age  number
0    0       0
1    1       2
2    2       4
3    3       6
4    4       8

In [13]:
df.set_index('age')

     number
age
0         0
1         2
2         4
3         6
4         8
5        10
6        12
7        14
8        16
9        18
10       20
11       22
12       24
13       26
14       28
15       30
16       32
17       34
18       36
19       38
20       40
21       42
22       44
23       46
24       48
25       50
26       52
27       54
28       56
29       58
30       60
31       62
32       64
33       66
34       68
35       70
36       72
37       74
38       76
39       78
40       80
41       82
42       84
43       86
44       88
45       90
46       92
47       94
48       96
49       98